/* Renders this project's own stand-in samples that are plain signals to WAV files in a folder, so they ship as files you can
 * open, edit or replace, and are loaded by the plugin like any WAV of your own (see src/samples.h):
 *   - slots 1-10, the noises, as "<number> <name>.wav";
 *   - slot 367 ("Sine 130.81 Hz"), as one cycle;
 *   - the 96 wave slots (368-463) as one WAV of single cycles with a cue point at each, named "...cycles...".
 * Each file carries a LIST/INFO comment saying it is a generated stand-in, not the instrument's audio. The synthesis is seeded, so
 * the same files come out every time.
 *   gcc -O1 -Isrc -o /tmp/render_samples tools/render_samples.c src/samples.c src/sample_names.c -lm && /tmp/render_samples standins */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "samples.h"

static const char NOTE[] = "Stand-in generated by Sturm (tools/render_samples.c); not audio from any instrument.";

static void p32(FILE *f, uint32_t v) { fputc(v, f); fputc(v >> 8, f); fputc(v >> 16, f); fputc(v >> 24, f); }
static void p16(FILE *f, uint32_t v) { fputc(v, f); fputc(v >> 8, f); }

/* 16-bit mono 44.1 kHz; cue points (frame offsets) when ncue > 0 */
static void wav_out(const char *path, const int16_t *x, int n, const uint32_t *cue, int ncue) {
    FILE *f = fopen(path, "wb");
    if (!f) { perror(path); exit(1); }
    uint32_t nl = (uint32_t)strlen(NOTE) + 1, nlp = nl + (nl & 1), list = 4 + 8 + nlp;      /* "INFO" + the ICMT chunk */
    uint32_t cuesz = ncue ? 8 + 4 + 24 * (uint32_t)ncue : 0;
    uint32_t total = 4 + 8 + 16 + 8 + 2 * (uint32_t)n + 8 + list + cuesz;
    fwrite("RIFF", 1, 4, f); p32(f, total); fwrite("WAVE", 1, 4, f);
    fwrite("fmt ", 1, 4, f); p32(f, 16); p16(f, 1); p16(f, 1); p32(f, 44100); p32(f, 88200); p16(f, 2); p16(f, 16);
    fwrite("data", 1, 4, f); p32(f, 2 * (uint32_t)n);
    for (int i = 0; i < n; i++) p16(f, (uint16_t)x[i]);
    fwrite("LIST", 1, 4, f); p32(f, list); fwrite("INFO", 1, 4, f);
    fwrite("ICMT", 1, 4, f); p32(f, nl); fwrite(NOTE, 1, nl, f); if (nl & 1) fputc(0, f);
    if (ncue) {
        fwrite("cue ", 1, 4, f); p32(f, 4 + 24 * (uint32_t)ncue); p32(f, (uint32_t)ncue);
        for (int i = 0; i < ncue; i++) {
            p32(f, (uint32_t)i + 1); p32(f, cue[i]); fwrite("data", 1, 4, f); p32(f, 0); p32(f, 0); p32(f, cue[i]);
        }
    }
    fclose(f);
}

static void cycle16(tp_samples_t *s, int k, int16_t *out) {
    const float *t = samples_wave(s, k, 0);
    for (int i = 0; i < TP_WLEN; i++) out[i] = (int16_t)lrintf(fmaxf(-1, fminf(1, t[i] * 0.99f)) * 32767);
}

int main(int argc, char **argv) {
    if (argc != 2) { fprintf(stderr, "usage: render_samples OUTDIR\n"); return 2; }
    char path[1024];
    tp_samples_t *s = samples_open();
    for (int k = 1; k <= 10; k++) {
        const tp_sample_t *sm = samples_get(s, k);
        snprintf(path, sizeof path, "%s/%03d %s.wav", argv[1], k, TP_SAMPLE_NAMES[k]);
        wav_out(path, sm->data, sm->len, NULL, 0);
    }
    int16_t cyc[TP_WLEN];
    samples_get(s, TP_FIRST_WAVE - 1);
    cycle16(s, TP_FIRST_WAVE - 1, cyc);
    snprintf(path, sizeof path, "%s/%03d %s.wav", argv[1], TP_FIRST_WAVE - 1, TP_SAMPLE_NAMES[TP_FIRST_WAVE - 1]);
    wav_out(path, cyc, TP_WLEN, NULL, 0);
    int nw = TP_NSAMPLES - TP_FIRST_WAVE;
    int16_t *all = malloc(sizeof(int16_t) * TP_WLEN * (size_t)nw);
    uint32_t *cue = malloc(sizeof(uint32_t) * (size_t)nw);
    for (int i = 0; i < nw; i++) { samples_get(s, TP_FIRST_WAVE + i); cycle16(s, TP_FIRST_WAVE + i, all + i * TP_WLEN); cue[i] = (uint32_t)(i * TP_WLEN); }
    snprintf(path, sizeof path, "%s/Sturm VS waves cycles.wav", argv[1]);
    wav_out(path, all, TP_WLEN * nw, cue, nw);
    free(all); free(cue);
    samples_close(s);
    return 0;
}
