/* Oscillator 3/4 sample names in the instrument's order (manual v1.4 p. 80-84); 0 = Osc Off. Names only: the sample audio
 * is not in any public file, so the plugin plays stand-ins of its own (src/samples.c) or your WAVs. */
#include "samples.h"
const char *const TP_SAMPLE_NAMES[TP_NSAMPLES] = {
    "Osc Off", "White Noise", "Pink Noise", "Green Noise", "Resonant 4K Noise", "Soft Noise", "Cicada", "Buzzed",
    "Chain Link", "Grinder", "420 HighPass Noise", "Tight Boom", "Porky", "Hollow Thud", "Hollow Head", "Mid Kick",
    "Slap Kick", "Thwang Kick", "Resonant K", "Boom Kick", "Quickick", "Punchy Kick", "Nice", "Short n Sweet", "Bumpy",
    "Loose", "Solid Thump", "Upfront", "Good Kick", "Metallic", "Square", "Beefy", "Flat", "Shorty Thud",
    "SCI Tom Cart Kick", "LM-1 Bass Drum", "LinnDrum Bass", "909ish", "808ish", "Long Time 808", "Cut the Mustard",
    "Electron K", "Flam", "Solid", "Early Nineties", "DigiBonk", "Woosh Kick", "Dirty Woosh", "Distorted 09",
    "Grain Granny", "Bit Reduction", "Back Scatter", "Crunchy", "Distorted Bump", "Reversed", "Orangey", "Snare Add Rim",
    "Mid Head", "Acoustic", "Good Hit", "Some Head", "Supra Snare", "Loose Ring", "Trick Snare Rim", "Resonant Loose",
    "Cool Rim", "Another Edge", "Cut Snare", "Muted Half Edge", "High Edge", "Cracker", "Light Rim", "Dry Rim", "Pickle-O",
    "Woody Side", "Side Stick", "Dead Side Stick", "Sharp Side", "Rim Cut", "808 Rim", "909 Rim", "AcouStick",
    "LinnDrum Rim", "Tom Cart Rim", "SweetDaOneSnare", "808ish", "Quickie", "Short n Tight", "High Short", "30 Day Snare",
    "Fat 9009", "Funk Sn", "LM-1 Snare", "LinnDrum SD", "Basicly", "Beatbox", "Machine", "Twin", "Dry", "Short Attack",
    "Digi 8", "CompuSnare", "Plastic", "Snare Trash", "Bucket", "Toy Drum", "Abrupt", "What Snare?", "Canned", "Dead Lid",
    "Tom Cart SD", "Classic", "DR55 SD", "Cold hit", "Zippy Thwack", "Crumbly", "70s Snare", "Bit Reduce SD", "Distant",
    "Filtered SD", "Oil Can", "Digital Sweetness", "Noisy Click", "Splatted Snare", "Broken SD", "Ghost of a Snare",
    "Video Game", "Caved Perc", "Reverse Snare", "Edge Heavy", "Pedal Edge", "Pedaled AM", "Half Edge", "Open Edge",
    "Sharp Closed", "Sharp Pedal", "Sharp Half", "Sharp Open", "Zilch Closed", "Zilch Pedal", "Zilch Open", "Pastey",
    "Pastey Half", "Heavy Closed", "Heavy Open", "Boss Closed", "Boss Open", "Dark Cl", "Dark Opn", "Amazon Closed",
    "Amazon Half", "Trash Hat", "Loose Open Hat", "Close Foot Pedal", "LM-1 Closed", "LM-1 Open", "LinnDrum HH Closed",
    "LinnDrum HH", "LinnDrum HH Open", "Close Tambo", "Tight Studio Hat", "Crack Hat", "Accent", "HH Dub Plate", "Dry Tap",
    "Peace Corp", "Old Timer", "Blu Pedal", "Fake", "Open Fat", "Abrasive", "Tic Tac", "Noise Hat", "Reversed",
    "Dirty Pedal", "Barely There", "Click", "Quiet", "Shorty HH", "One Foot Pedal", "8080 HH", "8080 Open", "808ish Maraca",
    "9009 HH", "9009 HH2", "Perc Hat", "DR55 HH", "Right Foot Pedal", "Another Perc", "Closing HH", "Small Hi Hat",
    "Unnatural", "Trip Hop HH", "Aliens", "Silver HH", "Kicky Hi Hat", "Large Edge Cymbal", "Zilch Crash", "Gong",
    "Pastey Hit", "45 Degree Dust", "Bell Crash", "Oriental Hit", "Higher Cymbal", "No Name Crash", "909ish",
    "LinnDrum Crash", "808ish Crash", "Hertz Cymbal", "Flat Ride", "Medium Bell", "Blue High Ride", "Small Gong",
    "Smooth Ride", "Shortcut", "LinnDrum Ride", "909ish Crash", "Tom Splash Cart", "Reverse CY", "Res Hi", "Res Mid",
    "Res Floor", "Nice Hi", "Nice Mid", "Nice Floor", "Punchy Hi", "Punchy Mid", "Punchy Low", "Hi Maple", "Mid Maple",
    "Low Maple", "Blue Tom Hi", "Blue Tom Lo", "Tonic Tom Hi", "Tonic Tom Low", "Acoustic Hi", "Acoustic Low", "Tom Splat",
    "Thudd Tom", "Wood World", "SCI Tom Cart", "LM-1 Hi Tom", "LM-1 Lo Tom", "LinnDrum TomHi", "LinnDrum TomMid",
    "LinnDrum TomLo", "808ish Hi Tom", "808ish Mid Tom", "808ish Low Tom", "909ish Tom Hi", "909ish Tom Mid",
    "909ish Tom Low", "Reverse Hi", "Reverse Mid", "Reverse Low", "Clap 9090", "Layered Clap", "Slap Clap", "Digi Clap",
    "NotDisClap", "PerClapsaLot", "LM-1 Clap", "LinnDrum Clap", "808ish", "9090", "Reverse Clap", "How Now", "Real Cow",
    "Tang Cowbell", "Dinky Cow", "Short Cow", "80s Cowbell", "LM-1 CowB", "LinnDrum CowB", "OG 808 Cow", "Reverse Cowbell",
    "Cross Stick", "Light Cross", "Low Cross", "Jam Block H", "Jam Block L", "Keys", "Guiro", "Castanet", "Drag That Click",
    "Moon Golf", "Real Shaker", "Cabasa A", "Cabasa B", "LM-1 Cabasa", "LinnDrum Cabasa", "Real Fingers", "Cute Drum Robot",
    "Digi Click", "Bit-o-Clap", "Hot Tabla Lo", "Hot Tabla Mid", "Hot Tabla Hi", "Hot Tabla Highest", "Tabla Bounce",
    "Udu Bounce", "Udu u Do 1", "Udu u Do 2", "What Conga", "Conga 1", "Conga 2", "Conga 3", "808ish Hi Conga",
    "808ish Lo Conga", "LM-1 CongaHi", "LM-1 CongaLo", "LinnDrum Conga", "Tambouriney", "Tambo Ring", "TamBell",
    "Metal Tamb", "Wood Tamb", "LM-1 Tamb", "LinnDrum Tamb", "Raucous Tamb", "Tri HiFi", "Short Triangle", "Noisy Bell",
    "Flexi A", "Flexi B", "Stick on Metal", "Clank", "Sounds Like?", "Abrupt Metal", "808ish Clave", "Rico Clave",
    "Phazey Click", "Coming Up", "Choked Perc", "Hollow Box Lid", "Oil Drum", "Canned Perc", "Half Full", "Pla-stick",
    "Punch n Drag", "Nutrino", "Solar Explosion", "Wrinkled", "Quark", "Particulate", "Hadron", "Flutter", "Broken Toy",
    "Click Reduction", "Fazzle", "Grunt", "Bucket Bottom", "Charged Porceline", "Brrrrr", "Shorted", "BeatBox", "Tap That",
    "Boxer2", "Flat Perc", "Flat Click", "Filtered Perc", "Vacant", "Hybrid Click", "SCI Tom Cart Laser", "SCI Tom Scratch",
    "Needle On", "Outta Time", "Sine 130.81 Hz", "Sine", "Sawtooth", "Square", "WmBell", "RdBell", "R2Bell", "W2Bell",
    "FmtBell", "FzReed", "FmtAOh", "FmtAhh", "Banjo1", "TriPlus", "DisBel", "Pulse2", "Pulse3", "SqrReed", "Oohh", "Eehh",
    "Feedback", "Piano1", "E.Pno", "M.Harm", "VS 23", "HiTop", "WmReed", "VS 26", "Hollow", "BellOrg", "BassBell", "Tine1",
    "SynBell", "VS 32", "Orient", "HighPipe", "Mass", "ReedOrg", "OrgAhh", "MelOrg", "Clarinet", "AhhFem", "AhhHom",
    "AhhBass", "RegVox", "Vocal1", "Vocal2", "Harmony", "Bass", "Guitar", "Nice", "WWind", "Oboe", "Harp", "Pipe", "Hack1",
    "Hack2", "Hack3", "Pinch", "BellHrm", "BellVox", "Hi Harm", "Hi Reed", "BellReed", "WmWhistl", "Corn", "Flute 2",
    "Med Pure", "Tuba", "FullBell", "Bell", "Pinch", "Clustr", "M.Pinch", "VoxPnch", "OrgPnch", "AhhPnch", "PnoOrg",
    "BrReed", "NoFund", "ReedHrm", "LiteFund", "MelOrg", "Bell Partials 1", "Bell", "VS 84", "VS 85", "VS 86", "VS 87",
    "VS 88", "VS 89", "VS 90", "VS 91", "VS 92", "Piano2", "Bell Partials 2", "VS 95",
};
